### ISSUE TITLE
List of three-ecsy core components

### ISSUE THREAD

**Issue by joshmarinacci** [ecsyjs/ecsy-three#1]
make a final(ish) list of components for the three bindings.

**Comment by joshmarinacci** [comment]
* Highlighted: indicates if an entity has been highlighted. Something else recognizes that the entity has been highlighted and modifies the actual threejs object (say, material swapping).
* Grabbable: indicates if a stationary object can be grabbed.
* Hands: represents a VRcontroller or other controller which can grab grabbable entities when it is near them. Handles all of the proximity detection, storing which thing has been grabbed, and swapping threejs nodes.

**Comment by robertlong** [comment]
We're in the process of figuring out our new core components and what belongs in core vs libraries. Closing this and we'll revisit in https://github.com/ecsyjs/ecsy-three/issues/36
