### ISSUE TITLE
SDFTextSystem: troika package rename

### ISSUE THREAD

**Issue by lojjic** [ecsyjs/ecsy-three#18]
I've recently promoted the standalone TextMesh implementation from a secondary build in `troika-3d-text` to its own package, `troika-three-text`. This means anyone using the old location will need to update to use the new package as of v0.29.0, and since I know it's in use in ecsy-three I'm opening this note as a courtesy "heads up!"

I think this should be a very simple change in SDFTextSystem:

```js
// OLD:
import { TextMesh } from "troika-3d-text/dist/textmesh-standalone.esm.js"
...
let foo = new TextMesh(opts)

// NEW:
import { Text } from "troika-three-text"
...
let foo = new Text(opts) 
```

The API should otherwise be identical as before the move. Please let me know if you encounter any issues when the time comes for you to update. Thanks!

**Comment by robertlong** [comment]
We've removed `troika-three-text` from the library so I'm going to close this.
