### ISSUE TITLE
Evaluate A-Frame core components to see which ones we could include on the core

### ISSUE THREAD

**Issue by fernandojsg** [ecsyjs/ecsy-three#3]
We could use the core components from A-Frame as a good reference for the ones we could include in the three-ecsy core.
I'll include the complete list they ship with 0.9.0 and we could go removing the ones we are not interested in and the ones we are going to implement, editing the list with the link to the issue or PR to discuss them

- [ ] animation
- [ ] background
- [ ] camera
- [ ] cursor
- [ ] daydream-controls
- [ ] debug
- [ ] embedded
- [ ] fog
- [ ] gearvr-controls
- [ ] geometry
- [ ] gltf-model
- [ ] keyboard-shortcuts
- [ ] laser-controls
- [ ] light
- [ ] line
- [ ] link
- [ ] loading-screen
- [ ] look-controls
- [ ] material
- [ ] obj-model
- [ ] oculus-go-controls
- [ ] oculus-touch-controls
- [ ] pool
- [ ] position
- [ ] raycaster
- [ ] rotation
- [ ] scale
- [ ] screenshot
- [ ] shadow
- [ ] sound
- [ ] stats
- [ ] text
- [ ] tracked-controls
- [ ] visible
- [ ] vive-controls
- [ ] vive-focus-controls
- [ ] vr-mode-ui
- [ ] wasd-controls
- [ ] windows-motion-controls

The curated list will be added to #1 with the components that will get shipped on the core

**Comment by feiss** [comment]
- [ ] particle system
- [ ] easy environment
- [ ] sky

**Comment by robertlong** [comment]
Moving discussion to https://github.com/ecsyjs/ecsy-three/issues/36
