### ISSUE TITLE
`removeAllComponents` will create weird behavior

### ISSUE THREAD

**Issue by DavidPeicho** [ecsyjs/ecsy-three#31]
Hi,

I may be wrong, but calling something like: `Entity. removeAllComponents()` will create issues with `Object3DComponent`.
Indeed, when calling [Entity.removeObject3DComponent](https://github.com/MozillaReality/ecsy-three/blob/dev/src/entity.js#L130) or [Entity.remove](https://github.com/MozillaReality/ecsy-three/blob/dev/src/entity.js#L154)

## Fix

1. A simple fix would be to do the cleaning / unparenting directly in the `reset()` method of the component. This method is always called.
2. A more general / robust solution would be to clear a bit what is called and when. Right now, it seems a bit odd to reset the component via its pool via a call to `dispose()`. It seems that everything should be handled by a final call to just the managers (component / entity). Also, calling `removeAllComponents` should obviously at some point call the `Entity.removeComponent`, otherwise people extending the default entity will anyway end up with those problem.

I can make a PR for that on Ecsy side if you want to.

Bye!

**Comment by robertlong** [comment]
I think for now we can just override `Entity.removeAllComponents()`, check if the entity has an `Object3DComponent` and call `Entity.removeObject3DComponent()`.

I do think we need a concept of a `ComponentManager` which can handle this sort of cleanup in a more extensible way.
