### ISSUE TITLE
Port the three.js webvr examples to three-ecsy

### ISSUE THREAD

**Issue by fernandojsg** [ecsyjs/ecsy-three#4]
Even so this is not going to be a just-webxr framework, and we will end up porting other examples, as a good starting point I'd like to port the webvr examples first:

- [ ] ballshooter
- [ ] cubes
- [ ] dragging
- [ ] lorenzattractor
- [ ] panorama
- [ ] paint
- [ ] rollercoaster
- [ ] sandbox
- [ ] sculpt
- [ ] video
- [ ] vive / paint
- [ ] vive / sculpt

**Comment by fernandojsg** [comment]
I'm starting with the panorama example

**Comment by robertlong** [comment]
Moving discussion to https://github.com/ecsyjs/ecsy-three/issues/36
